version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      db:
          condition: service_healthy

volumes:
  db:
